# This YAML assumes you have manually installed JDK 11 and set the JAVA_HOME_11_X64 variable

trigger:
- main

pool:
  name: 'My-Local-Agents'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Maven Project'
    steps:
    
    # --- CHANGE 1: THE JavaToolInstaller TASK HAS BEEN REMOVED ---

    - task: Maven@4
      displayName: 'Build with Maven'
      inputs:
        mavenPomFile: 'pom.xml'
        # --- CHANGE 2: MODIFIED THESE THREE LINES ---
        javaHomeOption: 'path'
        jdkDirectory: '$(JAVA_HOME_11_X64)'
        jdkArchitectureOption: 'x64'
        # --------------------------------------------
        publishJUnitTestResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployJob
    displayName: 'Deploy to Azure App Service'
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy WAR to App Service'
      inputs:
        azureSubscription: 'Azure-Subscription-Connection'
        appType: 'webAppLinux'
        appName: 'elango-my-shuttle-app'
        package: '$(Pipeline.Workspace)/drop/**/*.war'
        runtimeStack: 'TOMCAT|9.0-java11'
