# This YAML uses a manually installed JDK and correctly handles artifacts between stages

trigger:
- main

pool:
  name: 'My-Local-Agents'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Maven Project'
    steps:
    - task: Maven@4
      displayName: 'Build with Maven'
      inputs:
        mavenPomFile: 'pom.xml'
        javaHomeOption: 'path'
        jdkDirectory: '$(JAVA_HOME_11_X64)'
        jdkArchitectureOption: 'x64'
        publishJUnitTestResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    # --- NEW TASK TO COPY THE .WAR FILE ---
    # This copies the build output to the staging directory so it can be published.
    - task: CopyFiles@2
      displayName: 'Copy Artifact to Staging Directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/target'
        Contents: '*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    # ------------------------------------

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployJob
    displayName: 'Deploy to Azure App Service'
    steps:

    # This task is essential to bring the .war file from the Build stage into this stage.
    - task: DownloadBuildArtifacts@1
      displayName: 'Download Build Artifact'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(Pipeline.Workspace)'

    - task: AzureWebApp@1
      displayName: 'Deploy WAR to App Service'
      inputs:
        azureSubscription: 'Azure-Subscription-Connection'
        appType: 'webAppLinux'
        appName: 'my-shuttle-app'
        # The path is now correct because the Download task put the files in $(Pipeline.Workspace)
        package: '$(Pipeline.Workspace)/drop/**/*.war'
        runtimeStack: 'TOMCAT|9.0-java21'

