# This is a multi-stage pipeline for building and deploying a Java app

trigger:
- main

pool:
  name: 'My-Local-Agents'

stages:
# Build Stage - No changes here
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Maven Project'
    steps:
    - task: JavaToolInstaller@0
      displayName: 'Install JDK 11'
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'Prebuilt'

    - task: Maven@4
      displayName: 'Build with Maven'
      inputs:
        mavenPomFile: 'pom.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitTestResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# Deploy Stage - Corrected indentation is critical here
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployJob
    displayName: 'Deploy to Azure App Service'
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy WAR to App Service'
      inputs:
        azureSubscription: 'Azure-Subscription-Connection'
        appType: 'webAppLinux'
        appName: 'elango-my-shuttle-app'
        package: '$(Pipeline.Workspace)/drop/**/*.war'
        runtimeStack: 'TOMCAT|9.0-java11'
