# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# This pipeline builds a Java project with Maven
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # Use a Linux agent for Java builds

steps:
- task: Maven@3
  displayName: 'Build with Maven'
  inputs:
    mavenPomFile: 'pom.xml' # Or the correct path to your pom.xml if it's not in the root
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11' # Or 1.8, 1.17, etc., depending on your project
    jdkArchitectureOption: 'x64'
    publishJUnitTestResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package' # This compiles and packages the code into a .war or .jar file

- task: CopyFiles@2
  displayName: 'Copy Files to Artifact Staging Directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*.war' # Find the .war file
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'